
all: dtd xsd #web tidy xq java

dtd:
	xmllint --valid --noout donnees-master/data.xml

xsd:
	xmllint --noout --schema donnees-master/data.xsd donnees-master/data.xml

#web:



#tidy:


#xq:


#java:
